### ISSUE TITLE
can't load any document within the index

### ISSUE THREAD

**Issue by dantelmomsft** [aymenfurter/smartrag#10]
@aymenfurter when trying to upload or index a pdf document it fails. see below screenshot:
![image](https://github.com/user-attachments/assets/017690b1-e934-4716-8e36-f3ce9d360bff)
 below logs from container app:
 
![image](https://github.com/user-attachments/assets/5031050e-671b-4a7f-b67b-289885e20730)

**Comment by aymenfurter** [comment]
Hey @dantelmomsft 

this should be fixed with most recent image: ghcr.io/aymenfurter/smartrag/smartrag:174e97809e5c9721428f17b358a68ecc11dec04c

Cheers
Aymen
